// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type DeletedScore struct {
	User      string
	ScoreID   string
	DeletedAt time.Time
}

type DeletedSetlist struct {
	User      string
	SetlistID string
	DeletedAt time.Time
}

type DeletedTag struct {
	User      string
	TagID     string
	DeletedAt time.Time
}

type Score struct {
	User              string
	ID                string
	MetadataUpdatedAt time.Time
	FileUpdatedAt     time.Time
	FileType          string
	Title             string
	MetadataJson      []byte
	Changed           time.Time
}

type Setlist struct {
	User      string
	ID        string
	UpdatedAt time.Time
	Name      string
	Changed   time.Time
}

type Tag struct {
	User      string
	ID        string
	UpdatedAt time.Time
	Name      string
	Color     int64
	Changed   time.Time
}

type User struct {
	Name         string
	PasswordHash string
	CreatedAt    time.Time
}
