// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type AuthKey struct {
	Key       string
	User      string
	CreatedAt time.Time
	LastUsed  time.Time
}

type User struct {
	Name         string
	PasswordHash string
	CreatedAt    time.Time
}
