// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: practice.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const addExerciseScore = `-- name: AddExerciseScore :exec
INSERT INTO exercise_scores (user, exercise_id, position, score_id) VALUES (?, ?, ?, ?)
`

type AddExerciseScoreParams struct {
	User       string
	ExerciseID string
	Position   int64
	ScoreID    string
}

func (q *Queries) AddExerciseScore(ctx context.Context, arg AddExerciseScoreParams) error {
	_, err := q.db.ExecContext(ctx, addExerciseScore,
		arg.User,
		arg.ExerciseID,
		arg.Position,
		arg.ScoreID,
	)
	return err
}

const addPracticeRoutineEntry = `-- name: AddPracticeRoutineEntry :exec
INSERT INTO practice_routine_entries (user, id, routine_id, position, exercise_id, metadata_json) VALUES (?, ?, ?, ?, ?, ?)
`

type AddPracticeRoutineEntryParams struct {
	User         string
	ID           string
	RoutineID    string
	Position     int64
	ExerciseID   string
	MetadataJson []byte
}

func (q *Queries) AddPracticeRoutineEntry(ctx context.Context, arg AddPracticeRoutineEntryParams) error {
	_, err := q.db.ExecContext(ctx, addPracticeRoutineEntry,
		arg.User,
		arg.ID,
		arg.RoutineID,
		arg.Position,
		arg.ExerciseID,
		arg.MetadataJson,
	)
	return err
}

const addPracticeSessionEntry = `-- name: AddPracticeSessionEntry :exec
INSERT INTO practice_session_entries (user, id, session_id, exercise_id, routine_entry_id, metadata_json) VALUES (?, ?, ?, ?, ?, ?)
`

type AddPracticeSessionEntryParams struct {
	User           string
	ID             string
	SessionID      string
	ExerciseID     string
	RoutineEntryID sql.NullString
	MetadataJson   []byte
}

func (q *Queries) AddPracticeSessionEntry(ctx context.Context, arg AddPracticeSessionEntryParams) error {
	_, err := q.db.ExecContext(ctx, addPracticeSessionEntry,
		arg.User,
		arg.ID,
		arg.SessionID,
		arg.ExerciseID,
		arg.RoutineEntryID,
		arg.MetadataJson,
	)
	return err
}

const assignExerciseTag = `-- name: AssignExerciseTag :exec
INSERT INTO exercise_tags (user, exercise_id, tag_id) VALUES (?, ?, ?) ON CONFLICT (user, exercise_id, tag_id) DO NOTHING
`

type AssignExerciseTagParams struct {
	User       string
	ExerciseID string
	TagID      string
}

func (q *Queries) AssignExerciseTag(ctx context.Context, arg AssignExerciseTagParams) error {
	_, err := q.db.ExecContext(ctx, assignExerciseTag, arg.User, arg.ExerciseID, arg.TagID)
	return err
}

const createDeletedExerciseCategoryMarker = `-- name: CreateDeletedExerciseCategoryMarker :exec
INSERT INTO deleted_exercise_categories (category_id, user, deleted_at) VALUES (?, ?, unixepoch())
`

type CreateDeletedExerciseCategoryMarkerParams struct {
	CategoryID string
	User       string
}

func (q *Queries) CreateDeletedExerciseCategoryMarker(ctx context.Context, arg CreateDeletedExerciseCategoryMarkerParams) error {
	_, err := q.db.ExecContext(ctx, createDeletedExerciseCategoryMarker, arg.CategoryID, arg.User)
	return err
}

const createDeletedExerciseMarker = `-- name: CreateDeletedExerciseMarker :exec
INSERT INTO deleted_exercises (exercise_id, user, deleted_at) VALUES (?, ?, unixepoch())
`

type CreateDeletedExerciseMarkerParams struct {
	ExerciseID string
	User       string
}

func (q *Queries) CreateDeletedExerciseMarker(ctx context.Context, arg CreateDeletedExerciseMarkerParams) error {
	_, err := q.db.ExecContext(ctx, createDeletedExerciseMarker, arg.ExerciseID, arg.User)
	return err
}

const createDeletedPracticeRoutineMarker = `-- name: CreateDeletedPracticeRoutineMarker :exec
INSERT INTO deleted_practice_routines (routine_id, user, deleted_at) VALUES (?, ?, unixepoch())
`

type CreateDeletedPracticeRoutineMarkerParams struct {
	RoutineID string
	User      string
}

func (q *Queries) CreateDeletedPracticeRoutineMarker(ctx context.Context, arg CreateDeletedPracticeRoutineMarkerParams) error {
	_, err := q.db.ExecContext(ctx, createDeletedPracticeRoutineMarker, arg.RoutineID, arg.User)
	return err
}

const createDeletedPracticeSessionMarker = `-- name: CreateDeletedPracticeSessionMarker :exec
INSERT INTO deleted_practice_sessions (session_id, user, deleted_at) VALUES (?, ?, unixepoch())
`

type CreateDeletedPracticeSessionMarkerParams struct {
	SessionID string
	User      string
}

func (q *Queries) CreateDeletedPracticeSessionMarker(ctx context.Context, arg CreateDeletedPracticeSessionMarkerParams) error {
	_, err := q.db.ExecContext(ctx, createDeletedPracticeSessionMarker, arg.SessionID, arg.User)
	return err
}

const deleteDeletedExerciseCategoryMarker = `-- name: DeleteDeletedExerciseCategoryMarker :exec
DELETE FROM deleted_exercise_categories WHERE user = ? AND category_id = ?
`

type DeleteDeletedExerciseCategoryMarkerParams struct {
	User       string
	CategoryID string
}

func (q *Queries) DeleteDeletedExerciseCategoryMarker(ctx context.Context, arg DeleteDeletedExerciseCategoryMarkerParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeletedExerciseCategoryMarker, arg.User, arg.CategoryID)
	return err
}

const deleteDeletedExerciseMarker = `-- name: DeleteDeletedExerciseMarker :exec
DELETE FROM deleted_exercises WHERE user = ? AND exercise_id = ?
`

type DeleteDeletedExerciseMarkerParams struct {
	User       string
	ExerciseID string
}

func (q *Queries) DeleteDeletedExerciseMarker(ctx context.Context, arg DeleteDeletedExerciseMarkerParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeletedExerciseMarker, arg.User, arg.ExerciseID)
	return err
}

const deleteDeletedPracticeRoutineMarker = `-- name: DeleteDeletedPracticeRoutineMarker :exec
DELETE FROM deleted_practice_routines WHERE user = ? AND routine_id = ?
`

type DeleteDeletedPracticeRoutineMarkerParams struct {
	User      string
	RoutineID string
}

func (q *Queries) DeleteDeletedPracticeRoutineMarker(ctx context.Context, arg DeleteDeletedPracticeRoutineMarkerParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeletedPracticeRoutineMarker, arg.User, arg.RoutineID)
	return err
}

const deleteDeletedPracticeSessionMarker = `-- name: DeleteDeletedPracticeSessionMarker :exec
DELETE FROM deleted_practice_sessions WHERE user = ? AND session_id = ?
`

type DeleteDeletedPracticeSessionMarkerParams struct {
	User      string
	SessionID string
}

func (q *Queries) DeleteDeletedPracticeSessionMarker(ctx context.Context, arg DeleteDeletedPracticeSessionMarkerParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeletedPracticeSessionMarker, arg.User, arg.SessionID)
	return err
}

const deleteExercise = `-- name: DeleteExercise :execresult
DELETE FROM exercises WHERE user = ? AND id = ?
`

type DeleteExerciseParams struct {
	User string
	ID   string
}

func (q *Queries) DeleteExercise(ctx context.Context, arg DeleteExerciseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteExercise, arg.User, arg.ID)
}

const deleteExerciseCategory = `-- name: DeleteExerciseCategory :execresult
DELETE FROM exercise_categories WHERE user = ? AND id = ?
`

type DeleteExerciseCategoryParams struct {
	User string
	ID   string
}

func (q *Queries) DeleteExerciseCategory(ctx context.Context, arg DeleteExerciseCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteExerciseCategory, arg.User, arg.ID)
}

const deletePracticeRoutine = `-- name: DeletePracticeRoutine :execresult
DELETE FROM practice_routines WHERE user = ? AND id = ?
`

type DeletePracticeRoutineParams struct {
	User string
	ID   string
}

func (q *Queries) DeletePracticeRoutine(ctx context.Context, arg DeletePracticeRoutineParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePracticeRoutine, arg.User, arg.ID)
}

const deletePracticeSession = `-- name: DeletePracticeSession :execresult
DELETE FROM practice_sessions WHERE user = ? AND id = ?
`

type DeletePracticeSessionParams struct {
	User string
	ID   string
}

func (q *Queries) DeletePracticeSession(ctx context.Context, arg DeletePracticeSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePracticeSession, arg.User, arg.ID)
}

const findDeletedExerciseCategoriesSince = `-- name: FindDeletedExerciseCategoriesSince :many
SELECT category_id, deleted_at FROM deleted_exercise_categories WHERE user = ? AND deleted_at > ?
`

type FindDeletedExerciseCategoriesSinceParams struct {
	User      string
	DeletedAt time.Time
}

type FindDeletedExerciseCategoriesSinceRow struct {
	CategoryID string
	DeletedAt  time.Time
}

func (q *Queries) FindDeletedExerciseCategoriesSince(ctx context.Context, arg FindDeletedExerciseCategoriesSinceParams) ([]FindDeletedExerciseCategoriesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, findDeletedExerciseCategoriesSince, arg.User, arg.DeletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDeletedExerciseCategoriesSinceRow{}
	for rows.Next() {
		var i FindDeletedExerciseCategoriesSinceRow
		if err := rows.Scan(&i.CategoryID, &i.DeletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDeletedExerciseCategoryMarker = `-- name: FindDeletedExerciseCategoryMarker :one
SELECT user, category_id, deleted_at FROM deleted_exercise_categories WHERE user = ? AND category_id = ?
`

type FindDeletedExerciseCategoryMarkerParams struct {
	User       string
	CategoryID string
}

func (q *Queries) FindDeletedExerciseCategoryMarker(ctx context.Context, arg FindDeletedExerciseCategoryMarkerParams) (DeletedExerciseCategory, error) {
	row := q.db.QueryRowContext(ctx, findDeletedExerciseCategoryMarker, arg.User, arg.CategoryID)
	var i DeletedExerciseCategory
	err := row.Scan(&i.User, &i.CategoryID, &i.DeletedAt)
	return i, err
}

const findDeletedExerciseMarker = `-- name: FindDeletedExerciseMarker :one
SELECT user, exercise_id, deleted_at FROM deleted_exercises WHERE user = ? AND exercise_id = ?
`

type FindDeletedExerciseMarkerParams struct {
	User       string
	ExerciseID string
}

func (q *Queries) FindDeletedExerciseMarker(ctx context.Context, arg FindDeletedExerciseMarkerParams) (DeletedExercise, error) {
	row := q.db.QueryRowContext(ctx, findDeletedExerciseMarker, arg.User, arg.ExerciseID)
	var i DeletedExercise
	err := row.Scan(&i.User, &i.ExerciseID, &i.DeletedAt)
	return i, err
}

const findDeletedExercisesSince = `-- name: FindDeletedExercisesSince :many
SELECT exercise_id, deleted_at FROM deleted_exercises WHERE user = ? AND deleted_at > ?
`

type FindDeletedExercisesSinceParams struct {
	User      string
	DeletedAt time.Time
}

type FindDeletedExercisesSinceRow struct {
	ExerciseID string
	DeletedAt  time.Time
}

func (q *Queries) FindDeletedExercisesSince(ctx context.Context, arg FindDeletedExercisesSinceParams) ([]FindDeletedExercisesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, findDeletedExercisesSince, arg.User, arg.DeletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDeletedExercisesSinceRow{}
	for rows.Next() {
		var i FindDeletedExercisesSinceRow
		if err := rows.Scan(&i.ExerciseID, &i.DeletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDeletedPracticeRoutineMarker = `-- name: FindDeletedPracticeRoutineMarker :one
SELECT user, routine_id, deleted_at FROM deleted_practice_routines WHERE user = ? AND routine_id = ?
`

type FindDeletedPracticeRoutineMarkerParams struct {
	User      string
	RoutineID string
}

func (q *Queries) FindDeletedPracticeRoutineMarker(ctx context.Context, arg FindDeletedPracticeRoutineMarkerParams) (DeletedPracticeRoutine, error) {
	row := q.db.QueryRowContext(ctx, findDeletedPracticeRoutineMarker, arg.User, arg.RoutineID)
	var i DeletedPracticeRoutine
	err := row.Scan(&i.User, &i.RoutineID, &i.DeletedAt)
	return i, err
}

const findDeletedPracticeRoutinesSince = `-- name: FindDeletedPracticeRoutinesSince :many
SELECT routine_id, deleted_at FROM deleted_practice_routines WHERE user = ? AND deleted_at > ?
`

type FindDeletedPracticeRoutinesSinceParams struct {
	User      string
	DeletedAt time.Time
}

type FindDeletedPracticeRoutinesSinceRow struct {
	RoutineID string
	DeletedAt time.Time
}

func (q *Queries) FindDeletedPracticeRoutinesSince(ctx context.Context, arg FindDeletedPracticeRoutinesSinceParams) ([]FindDeletedPracticeRoutinesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, findDeletedPracticeRoutinesSince, arg.User, arg.DeletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDeletedPracticeRoutinesSinceRow{}
	for rows.Next() {
		var i FindDeletedPracticeRoutinesSinceRow
		if err := rows.Scan(&i.RoutineID, &i.DeletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDeletedPracticeSessionMarker = `-- name: FindDeletedPracticeSessionMarker :one
SELECT user, session_id, deleted_at FROM deleted_practice_sessions WHERE user = ? AND session_id = ?
`

type FindDeletedPracticeSessionMarkerParams struct {
	User      string
	SessionID string
}

func (q *Queries) FindDeletedPracticeSessionMarker(ctx context.Context, arg FindDeletedPracticeSessionMarkerParams) (DeletedPracticeSession, error) {
	row := q.db.QueryRowContext(ctx, findDeletedPracticeSessionMarker, arg.User, arg.SessionID)
	var i DeletedPracticeSession
	err := row.Scan(&i.User, &i.SessionID, &i.DeletedAt)
	return i, err
}

const findDeletedPracticeSessionsSince = `-- name: FindDeletedPracticeSessionsSince :many
SELECT session_id, deleted_at FROM deleted_practice_sessions WHERE user = ? AND deleted_at > ?
`

type FindDeletedPracticeSessionsSinceParams struct {
	User      string
	DeletedAt time.Time
}

type FindDeletedPracticeSessionsSinceRow struct {
	SessionID string
	DeletedAt time.Time
}

func (q *Queries) FindDeletedPracticeSessionsSince(ctx context.Context, arg FindDeletedPracticeSessionsSinceParams) ([]FindDeletedPracticeSessionsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, findDeletedPracticeSessionsSince, arg.User, arg.DeletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDeletedPracticeSessionsSinceRow{}
	for rows.Next() {
		var i FindDeletedPracticeSessionsSinceRow
		if err := rows.Scan(&i.SessionID, &i.DeletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findExercise = `-- name: FindExercise :one
SELECT user, id, updated_at, name, category_id, metadata_json, changed FROM exercises WHERE user = ? AND id = ?
`

type FindExerciseParams struct {
	User string
	ID   string
}

func (q *Queries) FindExercise(ctx context.Context, arg FindExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, findExercise, arg.User, arg.ID)
	var i Exercise
	err := row.Scan(
		&i.User,
		&i.ID,
		&i.UpdatedAt,
		&i.Name,
		&i.CategoryID,
		&i.MetadataJson,
		&i.Changed,
	)
	return i, err
}

const findExerciseCategoriesChangedAfter = `-- name: FindExerciseCategoriesChangedAfter :many
SELECT user, id, updated_at, name, position, changed FROM exercise_categories WHERE user = ? AND changed > ? ORDER BY id
`

type FindExerciseCategoriesChangedAfterParams struct {
	User    string
	Changed time.Time
}

func (q *Queries) FindExerciseCategoriesChangedAfter(ctx context.Context, arg FindExerciseCategoriesChangedAfterParams) ([]ExerciseCategory, error) {
	rows, err := q.db.QueryContext(ctx, findExerciseCategoriesChangedAfter, arg.User, arg.Changed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExerciseCategory{}
	for rows.Next() {
		var i ExerciseCategory
		if err := rows.Scan(
			&i.User,
			&i.ID,
			&i.UpdatedAt,
			&i.Name,
			&i.Position,
			&i.Changed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findExerciseCategory = `-- name: FindExerciseCategory :one
SELECT user, id, updated_at, name, position, changed FROM exercise_categories WHERE user = ? AND id = ?
`

type FindExerciseCategoryParams struct {
	User string
	ID   string
}

func (q *Queries) FindExerciseCategory(ctx context.Context, arg FindExerciseCategoryParams) (ExerciseCategory, error) {
	row := q.db.QueryRowContext(ctx, findExerciseCategory, arg.User, arg.ID)
	var i ExerciseCategory
	err := row.Scan(
		&i.User,
		&i.ID,
		&i.UpdatedAt,
		&i.Name,
		&i.Position,
		&i.Changed,
	)
	return i, err
}

const findExerciseScoreIDsChangedAfter = `-- name: FindExerciseScoreIDsChangedAfter :many
SELECT exercise_scores.exercise_id, exercise_scores.score_id FROM exercise_scores
JOIN exercises ON exercises.user = exercise_scores.user AND exercises.id = exercise_scores.exercise_id
WHERE exercises.user = ? AND exercises.changed > ? ORDER BY exercise_scores.position
`

type FindExerciseScoreIDsChangedAfterParams struct {
	User    string
	Changed time.Time
}

type FindExerciseScoreIDsChangedAfterRow struct {
	ExerciseID string
	ScoreID    string
}

func (q *Queries) FindExerciseScoreIDsChangedAfter(ctx context.Context, arg FindExerciseScoreIDsChangedAfterParams) ([]FindExerciseScoreIDsChangedAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, findExerciseScoreIDsChangedAfter, arg.User, arg.Changed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindExerciseScoreIDsChangedAfterRow{}
	for rows.Next() {
		var i FindExerciseScoreIDsChangedAfterRow
		if err := rows.Scan(&i.ExerciseID, &i.ScoreID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findExerciseTagIDsChangedAfter = `-- name: FindExerciseTagIDsChangedAfter :many
SELECT exercise_tags.exercise_id, exercise_tags.tag_id FROM exercise_tags
JOIN exercises ON exercises.user = exercise_tags.user AND exercises.id = exercise_tags.exercise_id
WHERE exercises.user = ? AND exercises.changed > ?
`

type FindExerciseTagIDsChangedAfterParams struct {
	User    string
	Changed time.Time
}

type FindExerciseTagIDsChangedAfterRow struct {
	ExerciseID string
	TagID      string
}

func (q *Queries) FindExerciseTagIDsChangedAfter(ctx context.Context, arg FindExerciseTagIDsChangedAfterParams) ([]FindExerciseTagIDsChangedAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, findExerciseTagIDsChangedAfter, arg.User, arg.Changed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindExerciseTagIDsChangedAfterRow{}
	for rows.Next() {
		var i FindExerciseTagIDsChangedAfterRow
		if err := rows.Scan(&i.ExerciseID, &i.TagID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findExercisesChangedAfter = `-- name: FindExercisesChangedAfter :many
SELECT user, id, updated_at, name, category_id, metadata_json, changed FROM exercises WHERE user = ? AND changed > ? ORDER BY id
`

type FindExercisesChangedAfterParams struct {
	User    string
	Changed time.Time
}

func (q *Queries) FindExercisesChangedAfter(ctx context.Context, arg FindExercisesChangedAfterParams) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, findExercisesChangedAfter, arg.User, arg.Changed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.User,
			&i.ID,
			&i.UpdatedAt,
			&i.Name,
			&i.CategoryID,
			&i.MetadataJson,
			&i.Changed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPracticeRoutine = `-- name: FindPracticeRoutine :one
SELECT user, id, updated_at, name, metadata_json, changed FROM practice_routines WHERE user = ? AND id = ?
`

type FindPracticeRoutineParams struct {
	User string
	ID   string
}

func (q *Queries) FindPracticeRoutine(ctx context.Context, arg FindPracticeRoutineParams) (PracticeRoutine, error) {
	row := q.db.QueryRowContext(ctx, findPracticeRoutine, arg.User, arg.ID)
	var i PracticeRoutine
	err := row.Scan(
		&i.User,
		&i.ID,
		&i.UpdatedAt,
		&i.Name,
		&i.MetadataJson,
		&i.Changed,
	)
	return i, err
}

const findPracticeRoutineEntriesChangedAfter = `-- name: FindPracticeRoutineEntriesChangedAfter :many
SELECT practice_routine_entries.user, practice_routine_entries.id, practice_routine_entries.routine_id, practice_routine_entries.position, practice_routine_entries.exercise_id, practice_routine_entries.metadata_json FROM practice_routine_entries
JOIN practice_routines ON practice_routines.user = practice_routine_entries.user AND practice_routines.id = practice_routine_entries.routine_id
WHERE practice_routines.user = ? AND practice_routines.changed > ? ORDER BY practice_routine_entries.position
`

type FindPracticeRoutineEntriesChangedAfterParams struct {
	User    string
	Changed time.Time
}

func (q *Queries) FindPracticeRoutineEntriesChangedAfter(ctx context.Context, arg FindPracticeRoutineEntriesChangedAfterParams) ([]PracticeRoutineEntry, error) {
	rows, err := q.db.QueryContext(ctx, findPracticeRoutineEntriesChangedAfter, arg.User, arg.Changed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PracticeRoutineEntry{}
	for rows.Next() {
		var i PracticeRoutineEntry
		if err := rows.Scan(
			&i.User,
			&i.ID,
			&i.RoutineID,
			&i.Position,
			&i.ExerciseID,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPracticeRoutineEntry = `-- name: FindPracticeRoutineEntry :one
SELECT user, id, routine_id, position, exercise_id, metadata_json FROM practice_routine_entries WHERE user = ? AND id = ?
`

type FindPracticeRoutineEntryParams struct {
	User string
	ID   string
}

func (q *Queries) FindPracticeRoutineEntry(ctx context.Context, arg FindPracticeRoutineEntryParams) (PracticeRoutineEntry, error) {
	row := q.db.QueryRowContext(ctx, findPracticeRoutineEntry, arg.User, arg.ID)
	var i PracticeRoutineEntry
	err := row.Scan(
		&i.User,
		&i.ID,
		&i.RoutineID,
		&i.Position,
		&i.ExerciseID,
		&i.MetadataJson,
	)
	return i, err
}

const findPracticeRoutinesChangedAfter = `-- name: FindPracticeRoutinesChangedAfter :many
SELECT user, id, updated_at, name, metadata_json, changed FROM practice_routines WHERE user = ? AND changed > ? ORDER BY id
`

type FindPracticeRoutinesChangedAfterParams struct {
	User    string
	Changed time.Time
}

func (q *Queries) FindPracticeRoutinesChangedAfter(ctx context.Context, arg FindPracticeRoutinesChangedAfterParams) ([]PracticeRoutine, error) {
	rows, err := q.db.QueryContext(ctx, findPracticeRoutinesChangedAfter, arg.User, arg.Changed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PracticeRoutine{}
	for rows.Next() {
		var i PracticeRoutine
		if err := rows.Scan(
			&i.User,
			&i.ID,
			&i.UpdatedAt,
			&i.Name,
			&i.MetadataJson,
			&i.Changed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPracticeSession = `-- name: FindPracticeSession :one
SELECT user, id, updated_at, started_at, ended_at, routine_id, metadata_json, changed FROM practice_sessions WHERE user = ? AND id = ?
`

type FindPracticeSessionParams struct {
	User string
	ID   string
}

func (q *Queries) FindPracticeSession(ctx context.Context, arg FindPracticeSessionParams) (PracticeSession, error) {
	row := q.db.QueryRowContext(ctx, findPracticeSession, arg.User, arg.ID)
	var i PracticeSession
	err := row.Scan(
		&i.User,
		&i.ID,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.RoutineID,
		&i.MetadataJson,
		&i.Changed,
	)
	return i, err
}

const findPracticeSessionEntriesChangedAfter = `-- name: FindPracticeSessionEntriesChangedAfter :many
SELECT practice_session_entries.user, practice_session_entries.id, practice_session_entries.session_id, practice_session_entries.exercise_id, practice_session_entries.routine_entry_id, practice_session_entries.metadata_json FROM practice_session_entries
JOIN practice_sessions ON practice_sessions.user = practice_session_entries.user AND practice_sessions.id = practice_session_entries.session_id
WHERE practice_sessions.user = ? AND practice_sessions.changed > ? ORDER BY practice_session_entries.id
`

type FindPracticeSessionEntriesChangedAfterParams struct {
	User    string
	Changed time.Time
}

func (q *Queries) FindPracticeSessionEntriesChangedAfter(ctx context.Context, arg FindPracticeSessionEntriesChangedAfterParams) ([]PracticeSessionEntry, error) {
	rows, err := q.db.QueryContext(ctx, findPracticeSessionEntriesChangedAfter, arg.User, arg.Changed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PracticeSessionEntry{}
	for rows.Next() {
		var i PracticeSessionEntry
		if err := rows.Scan(
			&i.User,
			&i.ID,
			&i.SessionID,
			&i.ExerciseID,
			&i.RoutineEntryID,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPracticeSessionEntry = `-- name: FindPracticeSessionEntry :one
SELECT user, id, session_id, exercise_id, routine_entry_id, metadata_json FROM practice_session_entries WHERE user = ? AND id = ?
`

type FindPracticeSessionEntryParams struct {
	User string
	ID   string
}

func (q *Queries) FindPracticeSessionEntry(ctx context.Context, arg FindPracticeSessionEntryParams) (PracticeSessionEntry, error) {
	row := q.db.QueryRowContext(ctx, findPracticeSessionEntry, arg.User, arg.ID)
	var i PracticeSessionEntry
	err := row.Scan(
		&i.User,
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.RoutineEntryID,
		&i.MetadataJson,
	)
	return i, err
}

const findPracticeSessionsChangedAfter = `-- name: FindPracticeSessionsChangedAfter :many
SELECT user, id, updated_at, started_at, ended_at, routine_id, metadata_json, changed FROM practice_sessions WHERE user = ? AND changed > ? ORDER BY id
`

type FindPracticeSessionsChangedAfterParams struct {
	User    string
	Changed time.Time
}

func (q *Queries) FindPracticeSessionsChangedAfter(ctx context.Context, arg FindPracticeSessionsChangedAfterParams) ([]PracticeSession, error) {
	rows, err := q.db.QueryContext(ctx, findPracticeSessionsChangedAfter, arg.User, arg.Changed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PracticeSession{}
	for rows.Next() {
		var i PracticeSession
		if err := rows.Scan(
			&i.User,
			&i.ID,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.RoutineID,
			&i.MetadataJson,
			&i.Changed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseScoreIDs = `-- name: GetExerciseScoreIDs :many
SELECT score_id FROM exercise_scores WHERE user = ? AND exercise_id = ? ORDER BY position
`

type GetExerciseScoreIDsParams struct {
	User       string
	ExerciseID string
}

func (q *Queries) GetExerciseScoreIDs(ctx context.Context, arg GetExerciseScoreIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getExerciseScoreIDs, arg.User, arg.ExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var score_id string
		if err := rows.Scan(&score_id); err != nil {
			return nil, err
		}
		items = append(items, score_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseTagIDs = `-- name: GetExerciseTagIDs :many
SELECT tag_id FROM exercise_tags WHERE user = ? AND exercise_id = ?
`

type GetExerciseTagIDsParams struct {
	User       string
	ExerciseID string
}

func (q *Queries) GetExerciseTagIDs(ctx context.Context, arg GetExerciseTagIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getExerciseTagIDs, arg.User, arg.ExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag_id string
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPracticeRoutineEntries = `-- name: GetPracticeRoutineEntries :many
SELECT user, id, routine_id, position, exercise_id, metadata_json FROM practice_routine_entries WHERE user = ? AND routine_id = ? ORDER BY position
`

type GetPracticeRoutineEntriesParams struct {
	User      string
	RoutineID string
}

func (q *Queries) GetPracticeRoutineEntries(ctx context.Context, arg GetPracticeRoutineEntriesParams) ([]PracticeRoutineEntry, error) {
	rows, err := q.db.QueryContext(ctx, getPracticeRoutineEntries, arg.User, arg.RoutineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PracticeRoutineEntry{}
	for rows.Next() {
		var i PracticeRoutineEntry
		if err := rows.Scan(
			&i.User,
			&i.ID,
			&i.RoutineID,
			&i.Position,
			&i.ExerciseID,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPracticeSessionEntries = `-- name: GetPracticeSessionEntries :many
SELECT user, id, session_id, exercise_id, routine_entry_id, metadata_json FROM practice_session_entries WHERE user = ? AND session_id = ? ORDER BY id
`

type GetPracticeSessionEntriesParams struct {
	User      string
	SessionID string
}

func (q *Queries) GetPracticeSessionEntries(ctx context.Context, arg GetPracticeSessionEntriesParams) ([]PracticeSessionEntry, error) {
	rows, err := q.db.QueryContext(ctx, getPracticeSessionEntries, arg.User, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PracticeSessionEntry{}
	for rows.Next() {
		var i PracticeSessionEntry
		if err := rows.Scan(
			&i.User,
			&i.ID,
			&i.SessionID,
			&i.ExerciseID,
			&i.RoutineEntryID,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllExerciseScores = `-- name: RemoveAllExerciseScores :exec
DELETE FROM exercise_scores WHERE user = ? AND exercise_id = ?
`

type RemoveAllExerciseScoresParams struct {
	User       string
	ExerciseID string
}

func (q *Queries) RemoveAllExerciseScores(ctx context.Context, arg RemoveAllExerciseScoresParams) error {
	_, err := q.db.ExecContext(ctx, removeAllExerciseScores, arg.User, arg.ExerciseID)
	return err
}

const removeAllPracticeRoutineEntries = `-- name: RemoveAllPracticeRoutineEntries :exec
DELETE FROM practice_routine_entries WHERE user = ? AND routine_id = ?
`

type RemoveAllPracticeRoutineEntriesParams struct {
	User      string
	RoutineID string
}

func (q *Queries) RemoveAllPracticeRoutineEntries(ctx context.Context, arg RemoveAllPracticeRoutineEntriesParams) error {
	_, err := q.db.ExecContext(ctx, removeAllPracticeRoutineEntries, arg.User, arg.RoutineID)
	return err
}

const removeAllPracticeSessionEntries = `-- name: RemoveAllPracticeSessionEntries :exec
DELETE FROM practice_session_entries WHERE user = ? AND session_id = ?
`

type RemoveAllPracticeSessionEntriesParams struct {
	User      string
	SessionID string
}

func (q *Queries) RemoveAllPracticeSessionEntries(ctx context.Context, arg RemoveAllPracticeSessionEntriesParams) error {
	_, err := q.db.ExecContext(ctx, removeAllPracticeSessionEntries, arg.User, arg.SessionID)
	return err
}

const unassignAllExerciseTags = `-- name: UnassignAllExerciseTags :exec
DELETE FROM exercise_tags WHERE user = ? AND exercise_id = ?
`

type UnassignAllExerciseTagsParams struct {
	User       string
	ExerciseID string
}

func (q *Queries) UnassignAllExerciseTags(ctx context.Context, arg UnassignAllExerciseTagsParams) error {
	_, err := q.db.ExecContext(ctx, unassignAllExerciseTags, arg.User, arg.ExerciseID)
	return err
}

const upsertExercise = `-- name: UpsertExercise :exec
INSERT INTO exercises (id, user, updated_at, name, category_id, metadata_json, changed) VALUES (?, ?, ?, ?, ?, ?, unixepoch())
ON CONFLICT (user, id) DO UPDATE SET updated_at = excluded.updated_at, name = excluded.name, category_id = excluded.category_id, metadata_json = excluded.metadata_json, changed = excluded.changed
`

type UpsertExerciseParams struct {
	ID           string
	User         string
	UpdatedAt    time.Time
	Name         string
	CategoryID   sql.NullString
	MetadataJson []byte
}

func (q *Queries) UpsertExercise(ctx context.Context, arg UpsertExerciseParams) error {
	_, err := q.db.ExecContext(ctx, upsertExercise,
		arg.ID,
		arg.User,
		arg.UpdatedAt,
		arg.Name,
		arg.CategoryID,
		arg.MetadataJson,
	)
	return err
}

const upsertExerciseCategory = `-- name: UpsertExerciseCategory :exec
INSERT INTO exercise_categories (id, user, updated_at, name, position, changed) VALUES (?, ?, ?, ?, ?, unixepoch())
ON CONFLICT (user, id) DO UPDATE SET updated_at = excluded.updated_at, name = excluded.name, position = excluded.position, changed = excluded.changed
`

type UpsertExerciseCategoryParams struct {
	ID        string
	User      string
	UpdatedAt time.Time
	Name      string
	Position  int64
}

func (q *Queries) UpsertExerciseCategory(ctx context.Context, arg UpsertExerciseCategoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertExerciseCategory,
		arg.ID,
		arg.User,
		arg.UpdatedAt,
		arg.Name,
		arg.Position,
	)
	return err
}

const upsertPracticeRoutine = `-- name: UpsertPracticeRoutine :exec
INSERT INTO practice_routines (id, user, updated_at, name, metadata_json, changed) VALUES (?, ?, ?, ?, ?, unixepoch())
ON CONFLICT (user, id) DO UPDATE SET updated_at = excluded.updated_at, name = excluded.name, metadata_json = excluded.metadata_json, changed = excluded.changed
`

type UpsertPracticeRoutineParams struct {
	ID           string
	User         string
	UpdatedAt    time.Time
	Name         string
	MetadataJson []byte
}

func (q *Queries) UpsertPracticeRoutine(ctx context.Context, arg UpsertPracticeRoutineParams) error {
	_, err := q.db.ExecContext(ctx, upsertPracticeRoutine,
		arg.ID,
		arg.User,
		arg.UpdatedAt,
		arg.Name,
		arg.MetadataJson,
	)
	return err
}

const upsertPracticeSession = `-- name: UpsertPracticeSession :exec
INSERT INTO practice_sessions (id, user, updated_at, started_at, ended_at, routine_id, metadata_json, changed) VALUES (?, ?, ?, ?, ?, ?, ?, unixepoch())
ON CONFLICT (user, id) DO UPDATE SET updated_at = excluded.updated_at, started_at = excluded.started_at, ended_at = excluded.ended_at, routine_id = excluded.routine_id, metadata_json = excluded.metadata_json, changed = excluded.changed
`

type UpsertPracticeSessionParams struct {
	ID           string
	User         string
	UpdatedAt    time.Time
	StartedAt    time.Time
	EndedAt      sql.NullTime
	RoutineID    sql.NullString
	MetadataJson []byte
}

func (q *Queries) UpsertPracticeSession(ctx context.Context, arg UpsertPracticeSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertPracticeSession,
		arg.ID,
		arg.User,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.EndedAt,
		arg.RoutineID,
		arg.MetadataJson,
	)
	return err
}
