// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scores.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const assignTag = `-- name: AssignTag :exec
INSERT INTO score_tags (score_id, tag_id) VALUES (?, ?) ON CONFLICT (score_id,tag_id) DO NOTHING
`

type AssignTagParams struct {
	ScoreID string
	TagID   string
}

func (q *Queries) AssignTag(ctx context.Context, arg AssignTagParams) error {
	_, err := q.db.ExecContext(ctx, assignTag, arg.ScoreID, arg.TagID)
	return err
}

const createDeletedScoreMarker = `-- name: CreateDeletedScoreMarker :exec
INSERT INTO deleted_scores (score_id, deleted_at) VALUES (?, unixepoch())
`

func (q *Queries) CreateDeletedScoreMarker(ctx context.Context, scoreID string) error {
	_, err := q.db.ExecContext(ctx, createDeletedScoreMarker, scoreID)
	return err
}

const createDeletedTagMarker = `-- name: CreateDeletedTagMarker :exec
INSERT INTO deleted_tags (tag_id, deleted_at) VALUES (?, unixepoch())
`

func (q *Queries) CreateDeletedTagMarker(ctx context.Context, tagID string) error {
	_, err := q.db.ExecContext(ctx, createDeletedTagMarker, tagID)
	return err
}

const deleteScore = `-- name: DeleteScore :one
DELETE FROM scores WHERE user = ? AND id = ? RETURNING id, user, metadata_updated_at, file_updated_at, file_type, title, metadata_json, changed
`

type DeleteScoreParams struct {
	User string
	ID   string
}

func (q *Queries) DeleteScore(ctx context.Context, arg DeleteScoreParams) (Score, error) {
	row := q.db.QueryRowContext(ctx, deleteScore, arg.User, arg.ID)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.MetadataUpdatedAt,
		&i.FileUpdatedAt,
		&i.FileType,
		&i.Title,
		&i.MetadataJson,
		&i.Changed,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :execresult
DELETE FROM tags WHERE user = ? AND id = ?
`

type DeleteTagParams struct {
	User string
	ID   string
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTag, arg.User, arg.ID)
}

const findDeletedScoreMarker = `-- name: FindDeletedScoreMarker :one
SELECT score_id, deleted_at FROM deleted_scores WHERE score_id = ?
`

func (q *Queries) FindDeletedScoreMarker(ctx context.Context, scoreID string) (DeletedScore, error) {
	row := q.db.QueryRowContext(ctx, findDeletedScoreMarker, scoreID)
	var i DeletedScore
	err := row.Scan(&i.ScoreID, &i.DeletedAt)
	return i, err
}

const findDeletedTagMarker = `-- name: FindDeletedTagMarker :one
SELECT tag_id, deleted_at FROM deleted_tags WHERE tag_id = ?
`

func (q *Queries) FindDeletedTagMarker(ctx context.Context, tagID string) (DeletedTag, error) {
	row := q.db.QueryRowContext(ctx, findDeletedTagMarker, tagID)
	var i DeletedTag
	err := row.Scan(&i.TagID, &i.DeletedAt)
	return i, err
}

const findScore = `-- name: FindScore :one
SELECT id, user, metadata_updated_at, file_updated_at, file_type, title, metadata_json, changed FROM scores WHERE user = ? AND id = ?
`

type FindScoreParams struct {
	User string
	ID   string
}

func (q *Queries) FindScore(ctx context.Context, arg FindScoreParams) (Score, error) {
	row := q.db.QueryRowContext(ctx, findScore, arg.User, arg.ID)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.MetadataUpdatedAt,
		&i.FileUpdatedAt,
		&i.FileType,
		&i.Title,
		&i.MetadataJson,
		&i.Changed,
	)
	return i, err
}

const findScoresChangedAfterWithTagIds = `-- name: FindScoresChangedAfterWithTagIds :many
SELECT id, user, metadata_updated_at, file_updated_at, file_type, title, metadata_json, changed, score_id, tag_id FROM scores LEFT JOIN score_tags ON scores.id = score_tags.score_id
WHERE user = ? AND changed > ? AND file_type != 'none' ORDER BY scores.id
`

type FindScoresChangedAfterWithTagIdsParams struct {
	User    string
	Changed time.Time
}

type FindScoresChangedAfterWithTagIdsRow struct {
	ID                string
	User              string
	MetadataUpdatedAt time.Time
	FileUpdatedAt     time.Time
	FileType          string
	Title             string
	MetadataJson      []byte
	Changed           time.Time
	ScoreID           sql.NullString
	TagID             sql.NullString
}

func (q *Queries) FindScoresChangedAfterWithTagIds(ctx context.Context, arg FindScoresChangedAfterWithTagIdsParams) ([]FindScoresChangedAfterWithTagIdsRow, error) {
	rows, err := q.db.QueryContext(ctx, findScoresChangedAfterWithTagIds, arg.User, arg.Changed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindScoresChangedAfterWithTagIdsRow{}
	for rows.Next() {
		var i FindScoresChangedAfterWithTagIdsRow
		if err := rows.Scan(
			&i.ID,
			&i.User,
			&i.MetadataUpdatedAt,
			&i.FileUpdatedAt,
			&i.FileType,
			&i.Title,
			&i.MetadataJson,
			&i.Changed,
			&i.ScoreID,
			&i.TagID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTag = `-- name: FindTag :one
SELECT id, user, updated_at, name, color, changed FROM tags WHERE user = ? AND id = ?
`

type FindTagParams struct {
	User string
	ID   string
}

func (q *Queries) FindTag(ctx context.Context, arg FindTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, findTag, arg.User, arg.ID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.UpdatedAt,
		&i.Name,
		&i.Color,
		&i.Changed,
	)
	return i, err
}

const findTagsChangedAfter = `-- name: FindTagsChangedAfter :many
SELECT id, user, updated_at, name, color, changed FROM tags WHERE user = ? AND changed > ?
`

type FindTagsChangedAfterParams struct {
	User    string
	Changed time.Time
}

func (q *Queries) FindTagsChangedAfter(ctx context.Context, arg FindTagsChangedAfterParams) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, findTagsChangedAfter, arg.User, arg.Changed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.User,
			&i.UpdatedAt,
			&i.Name,
			&i.Color,
			&i.Changed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignedTagIDs = `-- name: GetAssignedTagIDs :many
SELECT tag_id FROM score_tags WHERE score_id = ?
`

func (q *Queries) GetAssignedTagIDs(ctx context.Context, scoreID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAssignedTagIDs, scoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag_id string
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignAllTags = `-- name: UnassignAllTags :exec
DELETE FROM score_tags WHERE score_id = ?
`

func (q *Queries) UnassignAllTags(ctx context.Context, scoreID string) error {
	_, err := q.db.ExecContext(ctx, unassignAllTags, scoreID)
	return err
}

const updateFileInfo = `-- name: UpdateFileInfo :execresult
UPDATE scores SET file_updated_at = ?, file_type = ? WHERE id = ? AND file_updated_at < ?
`

type UpdateFileInfoParams struct {
	FileUpdatedAt   time.Time
	FileType        string
	ID              string
	FileUpdatedAt_2 time.Time
}

func (q *Queries) UpdateFileInfo(ctx context.Context, arg UpdateFileInfoParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateFileInfo,
		arg.FileUpdatedAt,
		arg.FileType,
		arg.ID,
		arg.FileUpdatedAt_2,
	)
}

const upsertScore = `-- name: UpsertScore :exec
INSERT INTO scores (id, user, metadata_updated_at, file_updated_at, file_type, title, metadata_json, changed)
VALUES (?,?,?,0,'none',?,?,unixepoch())
ON CONFLICT DO UPDATE SET metadata_updated_at = excluded.metadata_updated_at, title = excluded.title, metadata_json = excluded.metadata_json, changed = excluded.changed
`

type UpsertScoreParams struct {
	ID                string
	User              string
	MetadataUpdatedAt time.Time
	Title             string
	MetadataJson      []byte
}

func (q *Queries) UpsertScore(ctx context.Context, arg UpsertScoreParams) error {
	_, err := q.db.ExecContext(ctx, upsertScore,
		arg.ID,
		arg.User,
		arg.MetadataUpdatedAt,
		arg.Title,
		arg.MetadataJson,
	)
	return err
}

const upsertTag = `-- name: UpsertTag :exec
INSERT INTO tags (id, user, updated_at, name, color, changed) VALUES (?, ?, ?, ?, ?, unixepoch())
ON CONFLICT (id) DO UPDATE SET updated_at = excluded.updated_at, name = excluded.name, color = excluded.color, changed = excluded.changed
`

type UpsertTagParams struct {
	ID        string
	User      string
	UpdatedAt time.Time
	Name      string
	Color     int64
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) error {
	_, err := q.db.ExecContext(ctx, upsertTag,
		arg.ID,
		arg.User,
		arg.UpdatedAt,
		arg.Name,
		arg.Color,
	)
	return err
}
