// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scores.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const assignTag = `-- name: AssignTag :exec
INSERT INTO score_tags (user, score_id, tag_id) VALUES (?, ?, ?) ON CONFLICT (user,score_id,tag_id) DO NOTHING
`

type AssignTagParams struct {
	User    string
	ScoreID string
	TagID   string
}

func (q *Queries) AssignTag(ctx context.Context, arg AssignTagParams) error {
	_, err := q.db.ExecContext(ctx, assignTag, arg.User, arg.ScoreID, arg.TagID)
	return err
}

const createDeletedScoreMarker = `-- name: CreateDeletedScoreMarker :exec
INSERT INTO deleted_scores (score_id, user, deleted_at) VALUES (?, ?, unixepoch())
`

type CreateDeletedScoreMarkerParams struct {
	ScoreID string
	User    string
}

func (q *Queries) CreateDeletedScoreMarker(ctx context.Context, arg CreateDeletedScoreMarkerParams) error {
	_, err := q.db.ExecContext(ctx, createDeletedScoreMarker, arg.ScoreID, arg.User)
	return err
}

const createDeletedTagMarker = `-- name: CreateDeletedTagMarker :exec
INSERT INTO deleted_tags (tag_id, user, deleted_at) VALUES (?, ?, unixepoch())
`

type CreateDeletedTagMarkerParams struct {
	TagID string
	User  string
}

func (q *Queries) CreateDeletedTagMarker(ctx context.Context, arg CreateDeletedTagMarkerParams) error {
	_, err := q.db.ExecContext(ctx, createDeletedTagMarker, arg.TagID, arg.User)
	return err
}

const deleteDeletedScoreMarker = `-- name: DeleteDeletedScoreMarker :exec
DELETE FROM deleted_scores WHERE user = ? AND score_id = ?
`

type DeleteDeletedScoreMarkerParams struct {
	User    string
	ScoreID string
}

func (q *Queries) DeleteDeletedScoreMarker(ctx context.Context, arg DeleteDeletedScoreMarkerParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeletedScoreMarker, arg.User, arg.ScoreID)
	return err
}

const deleteDeletedTagMarker = `-- name: DeleteDeletedTagMarker :exec
DELETE FROM deleted_tags WHERE user = ? AND tag_id = ?
`

type DeleteDeletedTagMarkerParams struct {
	User  string
	TagID string
}

func (q *Queries) DeleteDeletedTagMarker(ctx context.Context, arg DeleteDeletedTagMarkerParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeletedTagMarker, arg.User, arg.TagID)
	return err
}

const deleteScore = `-- name: DeleteScore :execresult
DELETE FROM scores WHERE user = ? AND id = ?
`

type DeleteScoreParams struct {
	User string
	ID   string
}

func (q *Queries) DeleteScore(ctx context.Context, arg DeleteScoreParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteScore, arg.User, arg.ID)
}

const deleteTag = `-- name: DeleteTag :execresult
DELETE FROM tags WHERE user = ? AND id = ?
`

type DeleteTagParams struct {
	User string
	ID   string
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTag, arg.User, arg.ID)
}

const findAllScoreIDs = `-- name: FindAllScoreIDs :many
SELECT user, id FROM scores
`

type FindAllScoreIDsRow struct {
	User string
	ID   string
}

func (q *Queries) FindAllScoreIDs(ctx context.Context) ([]FindAllScoreIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, findAllScoreIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllScoreIDsRow{}
	for rows.Next() {
		var i FindAllScoreIDsRow
		if err := rows.Scan(&i.User, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDeletedScoreMarker = `-- name: FindDeletedScoreMarker :one
SELECT user, score_id, deleted_at FROM deleted_scores WHERE user = ? AND score_id = ?
`

type FindDeletedScoreMarkerParams struct {
	User    string
	ScoreID string
}

func (q *Queries) FindDeletedScoreMarker(ctx context.Context, arg FindDeletedScoreMarkerParams) (DeletedScore, error) {
	row := q.db.QueryRowContext(ctx, findDeletedScoreMarker, arg.User, arg.ScoreID)
	var i DeletedScore
	err := row.Scan(&i.User, &i.ScoreID, &i.DeletedAt)
	return i, err
}

const findDeletedScoresSince = `-- name: FindDeletedScoresSince :many
SELECT score_id, deleted_at FROM deleted_scores WHERE user = ? AND deleted_at > ?
`

type FindDeletedScoresSinceParams struct {
	User      string
	DeletedAt time.Time
}

type FindDeletedScoresSinceRow struct {
	ScoreID   string
	DeletedAt time.Time
}

func (q *Queries) FindDeletedScoresSince(ctx context.Context, arg FindDeletedScoresSinceParams) ([]FindDeletedScoresSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, findDeletedScoresSince, arg.User, arg.DeletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDeletedScoresSinceRow{}
	for rows.Next() {
		var i FindDeletedScoresSinceRow
		if err := rows.Scan(&i.ScoreID, &i.DeletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDeletedTagMarker = `-- name: FindDeletedTagMarker :one
SELECT user, tag_id, deleted_at FROM deleted_tags WHERE user = ? AND tag_id = ?
`

type FindDeletedTagMarkerParams struct {
	User  string
	TagID string
}

func (q *Queries) FindDeletedTagMarker(ctx context.Context, arg FindDeletedTagMarkerParams) (DeletedTag, error) {
	row := q.db.QueryRowContext(ctx, findDeletedTagMarker, arg.User, arg.TagID)
	var i DeletedTag
	err := row.Scan(&i.User, &i.TagID, &i.DeletedAt)
	return i, err
}

const findDeletedTagsSince = `-- name: FindDeletedTagsSince :many
SELECT tag_id, deleted_at FROM deleted_tags WHERE user = ? AND deleted_at > ?
`

type FindDeletedTagsSinceParams struct {
	User      string
	DeletedAt time.Time
}

type FindDeletedTagsSinceRow struct {
	TagID     string
	DeletedAt time.Time
}

func (q *Queries) FindDeletedTagsSince(ctx context.Context, arg FindDeletedTagsSinceParams) ([]FindDeletedTagsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, findDeletedTagsSince, arg.User, arg.DeletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDeletedTagsSinceRow{}
	for rows.Next() {
		var i FindDeletedTagsSinceRow
		if err := rows.Scan(&i.TagID, &i.DeletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findScore = `-- name: FindScore :one
SELECT user, id, metadata_updated_at, file_updated_at, file_type, title, metadata_json, changed FROM scores WHERE user = ? AND id = ?
`

type FindScoreParams struct {
	User string
	ID   string
}

func (q *Queries) FindScore(ctx context.Context, arg FindScoreParams) (Score, error) {
	row := q.db.QueryRowContext(ctx, findScore, arg.User, arg.ID)
	var i Score
	err := row.Scan(
		&i.User,
		&i.ID,
		&i.MetadataUpdatedAt,
		&i.FileUpdatedAt,
		&i.FileType,
		&i.Title,
		&i.MetadataJson,
		&i.Changed,
	)
	return i, err
}

const findScoresChangedAfterWithTagIds = `-- name: FindScoresChangedAfterWithTagIds :many
SELECT scores.user, scores.id, scores.metadata_updated_at, scores.file_updated_at, scores.file_type, scores.title, scores.metadata_json, scores.changed, score_tags.tag_id FROM scores
LEFT JOIN score_tags ON scores.user = score_tags.user AND scores.id = score_tags.score_id
WHERE scores.user = ? AND changed > ? AND file_type != 'none' ORDER BY scores.id
`

type FindScoresChangedAfterWithTagIdsParams struct {
	User    string
	Changed time.Time
}

type FindScoresChangedAfterWithTagIdsRow struct {
	User              string
	ID                string
	MetadataUpdatedAt time.Time
	FileUpdatedAt     time.Time
	FileType          string
	Title             string
	MetadataJson      []byte
	Changed           time.Time
	TagID             sql.NullString
}

func (q *Queries) FindScoresChangedAfterWithTagIds(ctx context.Context, arg FindScoresChangedAfterWithTagIdsParams) ([]FindScoresChangedAfterWithTagIdsRow, error) {
	rows, err := q.db.QueryContext(ctx, findScoresChangedAfterWithTagIds, arg.User, arg.Changed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindScoresChangedAfterWithTagIdsRow{}
	for rows.Next() {
		var i FindScoresChangedAfterWithTagIdsRow
		if err := rows.Scan(
			&i.User,
			&i.ID,
			&i.MetadataUpdatedAt,
			&i.FileUpdatedAt,
			&i.FileType,
			&i.Title,
			&i.MetadataJson,
			&i.Changed,
			&i.TagID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTag = `-- name: FindTag :one
SELECT user, id, updated_at, name, color, changed FROM tags WHERE user = ? AND id = ?
`

type FindTagParams struct {
	User string
	ID   string
}

func (q *Queries) FindTag(ctx context.Context, arg FindTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, findTag, arg.User, arg.ID)
	var i Tag
	err := row.Scan(
		&i.User,
		&i.ID,
		&i.UpdatedAt,
		&i.Name,
		&i.Color,
		&i.Changed,
	)
	return i, err
}

const findTagsChangedAfter = `-- name: FindTagsChangedAfter :many
SELECT user, id, updated_at, name, color, changed FROM tags WHERE user = ? AND changed > ?
`

type FindTagsChangedAfterParams struct {
	User    string
	Changed time.Time
}

func (q *Queries) FindTagsChangedAfter(ctx context.Context, arg FindTagsChangedAfterParams) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, findTagsChangedAfter, arg.User, arg.Changed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.User,
			&i.ID,
			&i.UpdatedAt,
			&i.Name,
			&i.Color,
			&i.Changed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignedTagIDs = `-- name: GetAssignedTagIDs :many
SELECT tag_id FROM score_tags WHERE user = ? AND score_id = ?
`

type GetAssignedTagIDsParams struct {
	User    string
	ScoreID string
}

func (q *Queries) GetAssignedTagIDs(ctx context.Context, arg GetAssignedTagIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAssignedTagIDs, arg.User, arg.ScoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag_id string
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignAllTags = `-- name: UnassignAllTags :exec
DELETE FROM score_tags WHERE user = ? AND score_id = ?
`

type UnassignAllTagsParams struct {
	User    string
	ScoreID string
}

func (q *Queries) UnassignAllTags(ctx context.Context, arg UnassignAllTagsParams) error {
	_, err := q.db.ExecContext(ctx, unassignAllTags, arg.User, arg.ScoreID)
	return err
}

const updateFileInfo = `-- name: UpdateFileInfo :execresult
UPDATE scores SET file_updated_at = ?, file_type = ?, changed = unixepoch() WHERE user = ? AND id = ? AND file_updated_at < ?
`

type UpdateFileInfoParams struct {
	FileUpdatedAt   time.Time
	FileType        string
	User            string
	ID              string
	FileUpdatedAt_2 time.Time
}

func (q *Queries) UpdateFileInfo(ctx context.Context, arg UpdateFileInfoParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateFileInfo,
		arg.FileUpdatedAt,
		arg.FileType,
		arg.User,
		arg.ID,
		arg.FileUpdatedAt_2,
	)
}

const upsertScore = `-- name: UpsertScore :exec
INSERT INTO scores (id, user, metadata_updated_at, file_updated_at, file_type, title, metadata_json, changed)
VALUES (?,?,?,0,'none',?,?,unixepoch())
ON CONFLICT (user, id) DO UPDATE SET metadata_updated_at = excluded.metadata_updated_at, title = excluded.title, metadata_json = excluded.metadata_json, changed = excluded.changed
`

type UpsertScoreParams struct {
	ID                string
	User              string
	MetadataUpdatedAt time.Time
	Title             string
	MetadataJson      []byte
}

func (q *Queries) UpsertScore(ctx context.Context, arg UpsertScoreParams) error {
	_, err := q.db.ExecContext(ctx, upsertScore,
		arg.ID,
		arg.User,
		arg.MetadataUpdatedAt,
		arg.Title,
		arg.MetadataJson,
	)
	return err
}

const upsertTag = `-- name: UpsertTag :exec
INSERT INTO tags (id, user, updated_at, name, color, changed) VALUES (?, ?, ?, ?, ?, unixepoch())
ON CONFLICT (user, id) DO UPDATE SET updated_at = excluded.updated_at, name = excluded.name, color = excluded.color, changed = excluded.changed
`

type UpsertTagParams struct {
	ID        string
	User      string
	UpdatedAt time.Time
	Name      string
	Color     int64
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) error {
	_, err := q.db.ExecContext(ctx, upsertTag,
		arg.ID,
		arg.User,
		arg.UpdatedAt,
		arg.Name,
		arg.Color,
	)
	return err
}
