// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setlists.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const addSetlistEntry = `-- name: AddSetlistEntry :exec
INSERT INTO setlist_entries (setlist_id, position, score_id) VALUES (?, ?, ?)
`

type AddSetlistEntryParams struct {
	SetlistID string
	Position  int64
	ScoreID   string
}

func (q *Queries) AddSetlistEntry(ctx context.Context, arg AddSetlistEntryParams) error {
	_, err := q.db.ExecContext(ctx, addSetlistEntry, arg.SetlistID, arg.Position, arg.ScoreID)
	return err
}

const createDeletedSetlistMarker = `-- name: CreateDeletedSetlistMarker :exec
INSERT INTO deleted_setlists (setlist_id, user, deleted_at) VALUES (?, ?, unixepoch())
`

type CreateDeletedSetlistMarkerParams struct {
	SetlistID string
	User      string
}

func (q *Queries) CreateDeletedSetlistMarker(ctx context.Context, arg CreateDeletedSetlistMarkerParams) error {
	_, err := q.db.ExecContext(ctx, createDeletedSetlistMarker, arg.SetlistID, arg.User)
	return err
}

const deleteSetlist = `-- name: DeleteSetlist :execresult
DELETE FROM setlists WHERE user = ? AND id = ?
`

type DeleteSetlistParams struct {
	User string
	ID   string
}

func (q *Queries) DeleteSetlist(ctx context.Context, arg DeleteSetlistParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSetlist, arg.User, arg.ID)
}

const findDeletedSetlistIDsSince = `-- name: FindDeletedSetlistIDsSince :many
SELECT setlist_id FROM deleted_setlists WHERE user = ? AND deleted_at > ?
`

type FindDeletedSetlistIDsSinceParams struct {
	User      string
	DeletedAt time.Time
}

func (q *Queries) FindDeletedSetlistIDsSince(ctx context.Context, arg FindDeletedSetlistIDsSinceParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, findDeletedSetlistIDsSince, arg.User, arg.DeletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var setlist_id string
		if err := rows.Scan(&setlist_id); err != nil {
			return nil, err
		}
		items = append(items, setlist_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDeletedSetlistMarker = `-- name: FindDeletedSetlistMarker :one
SELECT setlist_id, user, deleted_at FROM deleted_setlists WHERE setlist_id = ?
`

func (q *Queries) FindDeletedSetlistMarker(ctx context.Context, setlistID string) (DeletedSetlist, error) {
	row := q.db.QueryRowContext(ctx, findDeletedSetlistMarker, setlistID)
	var i DeletedSetlist
	err := row.Scan(&i.SetlistID, &i.User, &i.DeletedAt)
	return i, err
}

const findSetlist = `-- name: FindSetlist :one
SELECT id, user, updated_at, name, changed FROM setlists WHERE id = ?
`

func (q *Queries) FindSetlist(ctx context.Context, id string) (Setlist, error) {
	row := q.db.QueryRowContext(ctx, findSetlist, id)
	var i Setlist
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.UpdatedAt,
		&i.Name,
		&i.Changed,
	)
	return i, err
}

const findSetlistByUser = `-- name: FindSetlistByUser :one
SELECT id, user, updated_at, name, changed FROM setlists WHERE user = ? AND id = ?
`

type FindSetlistByUserParams struct {
	User string
	ID   string
}

func (q *Queries) FindSetlistByUser(ctx context.Context, arg FindSetlistByUserParams) (Setlist, error) {
	row := q.db.QueryRowContext(ctx, findSetlistByUser, arg.User, arg.ID)
	var i Setlist
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.UpdatedAt,
		&i.Name,
		&i.Changed,
	)
	return i, err
}

const findSetlistsChangedAfterWithScoreIds = `-- name: FindSetlistsChangedAfterWithScoreIds :many
SELECT id, user, updated_at, name, changed, setlist_id, position, score_id FROM setlists LEFT JOIN setlist_entries ON setlists.id = setlist_entries.setlist_id
WHERE user = ? AND changed > ? ORDER BY setlists.id, setlist_entries.position
`

type FindSetlistsChangedAfterWithScoreIdsParams struct {
	User    string
	Changed time.Time
}

type FindSetlistsChangedAfterWithScoreIdsRow struct {
	ID        string
	User      string
	UpdatedAt time.Time
	Name      string
	Changed   time.Time
	SetlistID sql.NullString
	Position  sql.NullInt64
	ScoreID   sql.NullString
}

func (q *Queries) FindSetlistsChangedAfterWithScoreIds(ctx context.Context, arg FindSetlistsChangedAfterWithScoreIdsParams) ([]FindSetlistsChangedAfterWithScoreIdsRow, error) {
	rows, err := q.db.QueryContext(ctx, findSetlistsChangedAfterWithScoreIds, arg.User, arg.Changed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSetlistsChangedAfterWithScoreIdsRow{}
	for rows.Next() {
		var i FindSetlistsChangedAfterWithScoreIdsRow
		if err := rows.Scan(
			&i.ID,
			&i.User,
			&i.UpdatedAt,
			&i.Name,
			&i.Changed,
			&i.SetlistID,
			&i.Position,
			&i.ScoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetlistScoreIDs = `-- name: GetSetlistScoreIDs :many
SELECT score_id FROM setlist_entries WHERE setlist_id = ? ORDER BY position
`

func (q *Queries) GetSetlistScoreIDs(ctx context.Context, setlistID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getSetlistScoreIDs, setlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var score_id string
		if err := rows.Scan(&score_id); err != nil {
			return nil, err
		}
		items = append(items, score_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllSetlistEntries = `-- name: RemoveAllSetlistEntries :exec
DELETE FROM setlist_entries WHERE setlist_id = ?
`

func (q *Queries) RemoveAllSetlistEntries(ctx context.Context, setlistID string) error {
	_, err := q.db.ExecContext(ctx, removeAllSetlistEntries, setlistID)
	return err
}

const upsertSetlist = `-- name: UpsertSetlist :exec
INSERT INTO setlists (id, user, updated_at, name, changed) VALUES (?, ?, ?, ?, unixepoch())
ON CONFLICT (id) DO UPDATE SET updated_at = excluded.updated_at, name = excluded.name, changed = excluded.changed
`

type UpsertSetlistParams struct {
	ID        string
	User      string
	UpdatedAt time.Time
	Name      string
}

func (q *Queries) UpsertSetlist(ctx context.Context, arg UpsertSetlistParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetlist,
		arg.ID,
		arg.User,
		arg.UpdatedAt,
		arg.Name,
	)
	return err
}
