// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setlists.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const addSetlistEntry = `-- name: AddSetlistEntry :exec
INSERT INTO setlist_entries (user, setlist_id, position, score_id) VALUES (?, ?, ?, ?)
`

type AddSetlistEntryParams struct {
	User      string
	SetlistID string
	Position  int64
	ScoreID   string
}

func (q *Queries) AddSetlistEntry(ctx context.Context, arg AddSetlistEntryParams) error {
	_, err := q.db.ExecContext(ctx, addSetlistEntry,
		arg.User,
		arg.SetlistID,
		arg.Position,
		arg.ScoreID,
	)
	return err
}

const createDeletedSetlistMarker = `-- name: CreateDeletedSetlistMarker :exec
INSERT INTO deleted_setlists (setlist_id, user, deleted_at) VALUES (?, ?, unixepoch())
`

type CreateDeletedSetlistMarkerParams struct {
	SetlistID string
	User      string
}

func (q *Queries) CreateDeletedSetlistMarker(ctx context.Context, arg CreateDeletedSetlistMarkerParams) error {
	_, err := q.db.ExecContext(ctx, createDeletedSetlistMarker, arg.SetlistID, arg.User)
	return err
}

const deleteDeletedSetlistMarker = `-- name: DeleteDeletedSetlistMarker :exec
DELETE FROM deleted_setlists WHERE user = ? AND setlist_id = ?
`

type DeleteDeletedSetlistMarkerParams struct {
	User      string
	SetlistID string
}

func (q *Queries) DeleteDeletedSetlistMarker(ctx context.Context, arg DeleteDeletedSetlistMarkerParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeletedSetlistMarker, arg.User, arg.SetlistID)
	return err
}

const deleteSetlist = `-- name: DeleteSetlist :execresult
DELETE FROM setlists WHERE user = ? AND id = ?
`

type DeleteSetlistParams struct {
	User string
	ID   string
}

func (q *Queries) DeleteSetlist(ctx context.Context, arg DeleteSetlistParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSetlist, arg.User, arg.ID)
}

const findDeletedSetlistMarker = `-- name: FindDeletedSetlistMarker :one
SELECT user, setlist_id, deleted_at FROM deleted_setlists WHERE user = ? AND setlist_id = ?
`

type FindDeletedSetlistMarkerParams struct {
	User      string
	SetlistID string
}

func (q *Queries) FindDeletedSetlistMarker(ctx context.Context, arg FindDeletedSetlistMarkerParams) (DeletedSetlist, error) {
	row := q.db.QueryRowContext(ctx, findDeletedSetlistMarker, arg.User, arg.SetlistID)
	var i DeletedSetlist
	err := row.Scan(&i.User, &i.SetlistID, &i.DeletedAt)
	return i, err
}

const findDeletedSetlistsSince = `-- name: FindDeletedSetlistsSince :many
SELECT setlist_id, deleted_at FROM deleted_setlists WHERE user = ? AND deleted_at > ?
`

type FindDeletedSetlistsSinceParams struct {
	User      string
	DeletedAt time.Time
}

type FindDeletedSetlistsSinceRow struct {
	SetlistID string
	DeletedAt time.Time
}

func (q *Queries) FindDeletedSetlistsSince(ctx context.Context, arg FindDeletedSetlistsSinceParams) ([]FindDeletedSetlistsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, findDeletedSetlistsSince, arg.User, arg.DeletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDeletedSetlistsSinceRow{}
	for rows.Next() {
		var i FindDeletedSetlistsSinceRow
		if err := rows.Scan(&i.SetlistID, &i.DeletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSetlist = `-- name: FindSetlist :one
SELECT user, id, updated_at, name, changed FROM setlists WHERE user = ? AND id = ?
`

type FindSetlistParams struct {
	User string
	ID   string
}

func (q *Queries) FindSetlist(ctx context.Context, arg FindSetlistParams) (Setlist, error) {
	row := q.db.QueryRowContext(ctx, findSetlist, arg.User, arg.ID)
	var i Setlist
	err := row.Scan(
		&i.User,
		&i.ID,
		&i.UpdatedAt,
		&i.Name,
		&i.Changed,
	)
	return i, err
}

const findSetlistsChangedAfterWithScoreIds = `-- name: FindSetlistsChangedAfterWithScoreIds :many
SELECT setlists.user, setlists.id, setlists.updated_at, setlists.name, setlists.changed, setlist_entries.score_id FROM setlists
LEFT JOIN setlist_entries ON setlists.user = setlist_entries.user AND setlists.id = setlist_entries.setlist_id
WHERE setlists.user = ? AND changed > ? ORDER BY setlists.id, setlist_entries.position
`

type FindSetlistsChangedAfterWithScoreIdsParams struct {
	User    string
	Changed time.Time
}

type FindSetlistsChangedAfterWithScoreIdsRow struct {
	User      string
	ID        string
	UpdatedAt time.Time
	Name      string
	Changed   time.Time
	ScoreID   sql.NullString
}

func (q *Queries) FindSetlistsChangedAfterWithScoreIds(ctx context.Context, arg FindSetlistsChangedAfterWithScoreIdsParams) ([]FindSetlistsChangedAfterWithScoreIdsRow, error) {
	rows, err := q.db.QueryContext(ctx, findSetlistsChangedAfterWithScoreIds, arg.User, arg.Changed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSetlistsChangedAfterWithScoreIdsRow{}
	for rows.Next() {
		var i FindSetlistsChangedAfterWithScoreIdsRow
		if err := rows.Scan(
			&i.User,
			&i.ID,
			&i.UpdatedAt,
			&i.Name,
			&i.Changed,
			&i.ScoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetlistScoreIDs = `-- name: GetSetlistScoreIDs :many
SELECT score_id FROM setlist_entries WHERE user = ? AND setlist_id = ? ORDER BY position
`

type GetSetlistScoreIDsParams struct {
	User      string
	SetlistID string
}

func (q *Queries) GetSetlistScoreIDs(ctx context.Context, arg GetSetlistScoreIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getSetlistScoreIDs, arg.User, arg.SetlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var score_id string
		if err := rows.Scan(&score_id); err != nil {
			return nil, err
		}
		items = append(items, score_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllSetlistEntries = `-- name: RemoveAllSetlistEntries :exec
DELETE FROM setlist_entries WHERE user = ? AND setlist_id = ?
`

type RemoveAllSetlistEntriesParams struct {
	User      string
	SetlistID string
}

func (q *Queries) RemoveAllSetlistEntries(ctx context.Context, arg RemoveAllSetlistEntriesParams) error {
	_, err := q.db.ExecContext(ctx, removeAllSetlistEntries, arg.User, arg.SetlistID)
	return err
}

const upsertSetlist = `-- name: UpsertSetlist :exec
INSERT INTO setlists (id, user, updated_at, name, changed) VALUES (?, ?, ?, ?, unixepoch())
ON CONFLICT (user, id) DO UPDATE SET updated_at = excluded.updated_at, name = excluded.name, changed = excluded.changed
`

type UpsertSetlistParams struct {
	ID        string
	User      string
	UpdatedAt time.Time
	Name      string
}

func (q *Queries) UpsertSetlist(ctx context.Context, arg UpsertSetlistParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetlist,
		arg.ID,
		arg.User,
		arg.UpdatedAt,
		arg.Name,
	)
	return err
}
