// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const createAuthKey = `-- name: CreateAuthKey :exec
INSERT INTO auth_keys (key, user) VALUES (?, ?)
`

type CreateAuthKeyParams struct {
	Key  string
	User string
}

func (q *Queries) CreateAuthKey(ctx context.Context, arg CreateAuthKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAuthKey, arg.Key, arg.User)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (name, password_hash) VALUES (?, ?)
`

type CreateUserParams struct {
	Name         string
	PasswordHash []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Name, arg.PasswordHash)
	return err
}

const deleteAuthKey = `-- name: DeleteAuthKey :exec
DELETE FROM auth_keys WHERE auth_keys.user = ? AND auth_keys.key = ?
`

type DeleteAuthKeyParams struct {
	User string
	Key  string
}

func (q *Queries) DeleteAuthKey(ctx context.Context, arg DeleteAuthKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteAuthKey, arg.User, arg.Key)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE name = ?
`

func (q *Queries) DeleteUser(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, name)
	return err
}

const findAuthKey = `-- name: FindAuthKey :one
SELECT "key", user, created_at FROM auth_keys WHERE user = ? AND key = ?
`

type FindAuthKeyParams struct {
	User string
	Key  string
}

func (q *Queries) FindAuthKey(ctx context.Context, arg FindAuthKeyParams) (AuthKey, error) {
	row := q.db.QueryRowContext(ctx, findAuthKey, arg.User, arg.Key)
	var i AuthKey
	err := row.Scan(&i.Key, &i.User, &i.CreatedAt)
	return i, err
}

const findUser = `-- name: FindUser :one
SELECT name, password_hash, created_at FROM users WHERE name = ?
`

func (q *Queries) FindUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUser, name)
	var i User
	err := row.Scan(&i.Name, &i.PasswordHash, &i.CreatedAt)
	return i, err
}

const findUsers = `-- name: FindUsers :one
SELECT name, password_hash, created_at FROM users
`

func (q *Queries) FindUsers(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, findUsers)
	var i User
	err := row.Scan(&i.Name, &i.PasswordHash, &i.CreatedAt)
	return i, err
}
