// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const createAuthKey = `-- name: CreateAuthKey :exec
INSERT INTO auth_keys (key, user) VALUES (?, ?)
`

type CreateAuthKeyParams struct {
	Key  string
	User string
}

func (q *Queries) CreateAuthKey(ctx context.Context, arg CreateAuthKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAuthKey, arg.Key, arg.User)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (name, password_hash) VALUES (?, ?)
`

type CreateUserParams struct {
	Name         string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Name, arg.PasswordHash)
	return err
}

const deleteAuthKey = `-- name: DeleteAuthKey :exec
DELETE FROM auth_keys WHERE auth_keys.user = ? AND auth_keys.key = ?
`

type DeleteAuthKeyParams struct {
	User string
	Key  string
}

func (q *Queries) DeleteAuthKey(ctx context.Context, arg DeleteAuthKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteAuthKey, arg.User, arg.Key)
	return err
}

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM users WHERE name = ?
`

func (q *Queries) DeleteUser(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUser, name)
}

const findAuthKey = `-- name: FindAuthKey :one
SELECT "key", user, created_at, last_used FROM auth_keys WHERE user = ? AND key = ?
`

type FindAuthKeyParams struct {
	User string
	Key  string
}

func (q *Queries) FindAuthKey(ctx context.Context, arg FindAuthKeyParams) (AuthKey, error) {
	row := q.db.QueryRowContext(ctx, findAuthKey, arg.User, arg.Key)
	var i AuthKey
	err := row.Scan(
		&i.Key,
		&i.User,
		&i.CreatedAt,
		&i.LastUsed,
	)
	return i, err
}

const findUser = `-- name: FindUser :one
SELECT name, password_hash, created_at FROM users WHERE name = ?
`

func (q *Queries) FindUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUser, name)
	var i User
	err := row.Scan(&i.Name, &i.PasswordHash, &i.CreatedAt)
	return i, err
}

const findUsers = `-- name: FindUsers :many
SELECT name, password_hash, created_at FROM users
`

func (q *Queries) FindUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, findUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.Name, &i.PasswordHash, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserName = `-- name: UpdateUserName :execresult
UPDATE users SET name = ? WHERE name = ?
`

type UpdateUserNameParams struct {
	Name   string
	Name_2 string
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserName, arg.Name, arg.Name_2)
}

const updateUserPassword = `-- name: UpdateUserPassword :execresult
UPDATE users SET password_hash = ? WHERE name = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	Name         string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.Name)
}
